### ISSUE TITLE
[BUG] Popout Player Scrolling Up

### ISSUE THREAD

**Issue by AndrewDWhittaker** [SynQApp/Extension#61]
**Describe the bug**
After I start listening to music, the mini player scrolls up and hides the controls. I cannot scroll it back down.

**Music service**
YouTube Music

**To Reproduce**
1. Open YouTube Music
2. Start playing a playlist
3. Open mini player
4. The mini player display scrolls up and I hides the controls. I can only see the list.

**Expected behavior**
For the mini player to not automatically scroll and hide the controls so I can use the mini player for its intended use.

**Screenshots**
![2024-11-18 11_32_28-Bran-new Lovesong - YouTube Music](https://github.com/user-attachments/assets/c6394f50-bea6-4c9f-bbad-ca72595e1925)

**Device (please complete the following information):**
 - OS [Windows 11 Pro 23H2]
 - Browser [Brave]
 - Version [1.73.89]

**Additional context**
This issue just started happening this morning.

**Comment by tekkeon** [comment]
I was able to reproduce this issue on my Windows desktop. Very strange issue! I'll look into this and hopefully will get a fix for it soon.

**Comment by AndrewDWhittaker** [comment]
Thank you!

**Comment by tekkeon** [comment]
Hey @AndrewDWhittaker, I just completed the fix for this issue and have submitted the update to Chrome for review. Typically they approve our requests within 24 hours (often within just a few hours), so hopefully it should be out within a day! I'll update this issue one more time once we get the approval, and you can either wait for your browser to auto-update it, or if you uninstall and reinstall it, it will pull the latest version so you can get back to using it ASAP!

**Comment by tekkeon** [comment]
Dang they were quick, just got the notification that it was published and confirmed. Please let me know if it works on your end!

**Comment by AndrewDWhittaker** [comment]
It works now. Thanks!
